### ISSUE TITLE
Error - undefined method `chargeable_class=' for Pay:Module

### ISSUE THREAD

**Issue by grichardomi** [jasoncharnes/pay#60]
Does anyone know what could be cause of this error?

**Comment by excid3** [comment]
Make sure you're using the latest version directly from Github. I've got to cut a new release soon for Rubygems. 

I imagine that's probably the issue, since the `chargeable_class` setting has been added more recently.

https://github.com/jasoncharnes/pay/blob/master/lib/pay.rb#L16

**Comment by grichardomi** [comment]
Thanks!

**Comment by ykamin-booth** [comment]
Getting this error again after upgrading to V3. Does that mean you can no longer create your own pay_charge models?

**Comment by excid3** [comment]
This configuration has been removed since we're going to be managing the models in the gem going forward. Easier to maintain.

You can extend the Pay models to add functionality by including a module. https://github.com/pay-rails/pay/blob/master/docs/8_customizing_models.md

**Comment by ykamin-booth** [comment]
Ok, can you add that to the upgrade to V3 documentation?

**Comment by excid3** [comment]
Added to the UPGRADE.md doc: 27c30d2
